client:
    restEndpoints:
        getPositions: http://api.goeuro.com/api/v2/position/suggest/en/{location}

csv:
    fileName: locations.csv
    fileEncoding: UTF-8

logging:
    level:
        com.goeuro.assignment.Application: DEBUG
        org.springframework: OFF
